version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=brain
    networks:
      - my-network
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    volumes:
      - db:/var/lib/postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - my-network
    command: sh -c "yarn db:start && yarn start:dev"

volumes:
  db:

networks:
  my-network:
    driver: bridge